# Multi-stage build: install deps in a full image, run in a slim one.
# node:20-alpine ships an older bundled npm whose `npm ci` has known issues
# reading some lockfile-v3 entries generated by a newer npm (surfaced as
# false "Missing: X from lock file" errors) — pin a current npm before
# installing so the same npm major version writes and reads the lockfile.
FROM node:20-alpine AS deps
WORKDIR /app
RUN npm install -g npm@11
COPY backend/package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY backend/ .
RUN mkdir -p logs uploads

RUN addgroup -S nodejs && adduser -S nodejs -G nodejs && chown -R nodejs:nodejs /app
USER nodejs

EXPOSE 5000
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD node -e "require('http').get('http://localhost:5000/health', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"

CMD ["node", "src/server.js"]
