// One-time import of legacy vendor list ("vendor list.pdf" party register).
// Only fields that exist on Vendor.model.js are carried over — the source register
// also had address/GSTIN/credit-terms/banned-status columns, but those aren't
// SOP-mandated Vendor fields (see .claude/CLAUDE.md) so they're intentionally dropped here.
//
// A handful of rows read as internal ledger accounts rather than external suppliers
// (ACHAAR ACCOUNT, KITCHEN FMB, RAJU [CASH], VEG, VEG FMB NAGPUR) and a few names are
// near-duplicates of each other (BOMBAY CHICKEN variants, NEW ROYAL FOOD SERVICES
// PVT LTD / PVT.LTD, SHANTI DAIRY x2) — both were kept as-is, exactly as the source
// listed them, per explicit instruction not to merge or filter.

const legacyVendorsSeedData = [
  { name: 'A.B SALES CORPORATION', phone: '8823882694', email: 'absales.co2015gmai.com' },
  { name: 'ABID DAIRY' },
  { name: 'ABIS EXPORTS INDIA PVT LTD', phone: '7024230766' },
  { name: 'ACHAAR ACCOUNT' },
  { name: 'AJAZ FRUIT' },
  { name: 'ALI CHICKEN CENTER', phone: '9371742603' },
  { name: 'AMEY MARKETING' },
  { name: 'ANAND BAKERY' },
  { name: 'ANAND ENTERPRISES', contactPerson: 'RAJU MANGHANI', phone: '7122554885' },
  { name: 'ANNAPURNA FOOD PRODUCTS NX', phone: '7122763918' },
  { name: 'APNA MUTTON SHOP', phone: '9371229474' },
  { name: 'ARUN FUTANA' },
  { name: 'AYUSH FOOD' },
  { name: 'AYUSH FOODS THE NAMKEEN HUB', phone: '7122723021' },
  { name: 'BABLU KIRANA' },
  { name: 'BALAJI UDYOG', phone: '7354322444' },
  { name: 'BHURU BHAI ROTI WAALE' },
  { name: 'BIR ENTERPRISES', phone: '9890182152' },
  { name: 'BOMBAY CHICKEN', phone: '9371942294' },
  { name: 'BOMBAY CHICKEN & TRADERS', phone: '9370727581' },
  { name: 'BOMBAY CHICKEN PVT LTD', phone: '9370442294', email: 'bombaychickennaseer@gmail.com' },
  { name: 'DINDAYAL TULSHIRAM BISEN' },
  { name: 'DINDIYAL TULSI RAAM MANKAPUR' },
  { name: 'DIPESH HARISH GURNANI', phone: '9975723931', email: 'dipeshgurnani54@gmail.com' },
  { name: 'FRESH MILK' },
  { name: 'FRESH MOTTON & CHICKEN', phone: '9371990180' },
  { name: 'GUPTA JI [SALT]', phone: '7720859619' },
  { name: 'H.M QURBAN HUSAIN A. HUSAIN', phone: '7122733813' },
  { name: 'HAFEEZ BAKERY', phone: '9096449746' },
  { name: 'HAFIZ BAKERY' },
  { name: 'HAIDERY MASALE', phone: '9923131319' },
  { name: 'HAKIM KIRANA' },
  { name: 'HAKIMI MASALE' },
  { name: 'HALDIRAM"S' },
  { name: 'HARDIK TRADERS', phone: '9595277702' },
  { name: 'HARICHAND DADUMAL', phone: '9730620111' },
  { name: 'HYDERABAD EGG CENTER', phone: '8421791785' },
  { name: 'IB GROUP VIHIRGAON DRESS PLANT' },
  { name: 'IMPERIAL AGENCIES', phone: '9766918230' },
  { name: 'IMPERIAL STORES', phone: '9421806168' },
  { name: 'INDIAN BOLLIER' },
  { name: 'INDIAN FOOD PROCESSOR', phone: '9834042958' },
  { name: 'INDORE NAMKEEN' },
  { name: 'KABRA SALES AND MARKETING', phone: '9423636066' },
  { name: 'KESARIYA AGRO FOOD COTTAGE INDUSTRY', phone: '9370234328' },
  { name: 'KITCHEN FMB' },
  { name: 'KREME MILK FOODS' },
  { name: 'LAXMI AGENCY-NAGPUR' },
  { name: 'M.A. ENTERPRISE', phone: '9372308572' },
  { name: 'M.S. FLOUR MILL', phone: '9422126874' },
  { name: 'MA TRADERS' },
  { name: 'MADHAV TRADERS', email: 'madhavtrader@gmail.com' },
  { name: 'MANTRI TRADING PVT.LTD', email: 'mantrimtpl@gmail.com' },
  { name: 'MASHHOOR CHICKEN CENTER', phone: '9890648860' },
  { name: 'MINI MARKET', contactPerson: 'MINI', phone: '8055068744' },
  { name: 'MURTUZA MARFATIYA', phone: '9324311655' },
  { name: 'NARAYANDAS MAHESHKUMAR', phone: '7122760394' },
  { name: 'NARESH MILK CENTER', phone: '9834153122' },
  { name: 'NEW ROYAL FOOD SERVICES PVT LTD', phone: '931774931' },
  { name: 'NEW ROYAL FOOD SERVICES PVT.LTD', phone: '9371774938' },
  { name: 'NITIN DAIRY', phone: '9373120307' },
  { name: 'PARAS MARKETING', phone: '9850834443' },
  { name: 'PRAKASH SALES CENTRE' },
  { name: 'PREMIUM TEA COMPANY', phone: '7387555110', email: 'premiumteacompany@gmail.com' },
  { name: 'R.A. TRADERS', phone: '9826293029' },
  { name: 'RAHI TRADERS' },
  { name: 'RAILISH MATTON & CHICKEN SHOP', phone: '9370027295' },
  { name: 'RAJU [CASH]' },
  { name: 'RAZA EGG' },
  { name: 'RAZA [RAHIM] EGG' },
  { name: 'ROYAL FOOD SERVICES' },
  { name: 'SARTHI TRADERS' },
  { name: 'SHABBIR CHEMICAL' },
  { name: 'SHABIR CYCLE [SAFRA]' },
  { name: 'SHAH COMPANY', phone: '75069993111' },
  { name: 'SHANTI DAIRY' },
  { name: 'SHANTI DAIRY' },
  { name: 'SHRI BHAGWATI TRADERS', phone: '9890441808', email: 'singhaniashashikant16@gmail.com' },
  { name: 'SHRI SAI AGENCY' },
  { name: 'STAR ENTERPRISES', phone: '9860643279' },
  { name: 'SUPER CHICKEN & MUTTON CENTRE', phone: '7122582728' },
  { name: 'TAHA BHAI FAKRI' },
  { name: 'THE ROYAL FEAST', phone: '9764040629' },
  { name: 'VEG' },
  { name: 'VEG FMB NAGPUR' },
  { name: 'YASH MARKETING' },
];

module.exports = legacyVendorsSeedData;
